# Generated by Django 3.1.5 on 2021-01-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210124_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
