# Generated by Django 3.1.5 on 2021-01-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210124_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('s', 'Sport'), ('p', 'Politic'), ('so', 'Social'), ('e', 'Economy'), ('t', 'Technology'), ('l', 'Literature'), ('ed', 'Education'), ('ph', 'Philosophy'), ('o', 'Other')], default='t', max_length=10),
        ),
    ]
